CREATE TABLE IF NOT EXISTS employees (
    id SERIAL PRIMARY KEY,
    member_id INT UNIQUE NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    position VARCHAR(100) NOT NULL,
    salary NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);